# ------------------------------------------------------------------ #
#                                                                    #
#           SymPy CI script for Github Actions                       #
#                                                                    #
#   Runs each time a pull request is opened, pushed or merged        #
#                                                                    #
# ------------------------------------------------------------------ #

name: test
on: [push, pull_request]
jobs:

  # -------------------- Code quality ------------------------------ #

  code-quality:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: python -m pip install --upgrade pip
      - run: pip install mpmath flake8
      - run: bin/test quality
      - run: flake8 sympy

  # -------------------- Doctests ---------------------------------- #

  doctests:
    needs: code-quality

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install --upgrade pip
      - run: pip install mpmath
      - run: bin/doctest --force-colors
      - run: examples/all.py -q

  # -------------------- Test split 1/2 ---------------------------- #

  tests1:
    needs: code-quality

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install --upgrade pip
      - run: pip install mpmath
      - run: bin/test --force-colors --split=1/2

  # -------------------- Test split 2/2 ---------------------------- #

  tests2:
    needs: code-quality

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install --upgrade pip
      - run: pip install mpmath
      - run: bin/test --force-colors --split=2/2

  # -------------------- Slow test split 1/2 ----------------------- #

  slow1:
    needs: code-quality
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: python -m pip install --upgrade pip
      - run: pip install mpmath
      - run: TRAVIS_BUILD_NUMBER=true bin/test --force-colors --slow --timeout=595 --split=1/2

  # -------------------- Slow test split 2/2 ----------------------- #

  slow2:
    needs: code-quality
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: python -m pip install --upgrade pip
      - run: pip install mpmath
      - run: TRAVIS_BUILD_NUMBER=true bin/test --force-colors --slow --timeout=595 --split=2/2

  # -------------------- Optional dependency tests ----------------- #

  optional-dependencies:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: release/aptinstall.sh
      # Test external imports
      - run: release/venv_main/bin/python bin/test_external_imports.py
      - run: release/venv_main/bin/python bin/test_submodule_imports.py
      - run: release/venv_main/bin/python bin/test_executable.py
      # Test modules for specific dependencies
      - run: release/venv_main/bin/python bin/test_optional_dependencies.py

  # -------------------- Build the html/latex docs ----------------- #

  sphinx:
    needs: code-quality
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: release/aptinstall.sh
      - run: pip install -r release/requirements.txt
      - run: bin/test_sphinx.sh
